# Generated by Django 4.0.5 on 2022-07-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField(max_length=10)),
                ('ed', models.FloatField(max_length=10)),
                ('employ', models.FloatField(max_length=10)),
                ('debtinc', models.FloatField(max_length=10)),
                ('creddebt', models.FloatField(max_length=10)),
                ('othdebt', models.FloatField(max_length=10)),
            ],
        ),
    ]
