# Generated by Django 4.0.5 on 2022-07-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
